// topography.js — the AUTHORED non-vascular location axis. Content only; no logic.
//
// Three attributes, each earning its place in a pattern predicate (engine/multifocal.js):
//   lobe    — which cortical lobe (cortex keys only); a separation axis in its own right, because two
//             lesions in different lobes are separated in space even within one vascular territory
//   surface — CSF-bathed (meninges, cranial-nerve corridors, roots, cauda, chiasm, conus) vs deep
//             parenchyma. This is what separates leptomeningeal SEEDING from a parenchymal MASS.
//   system  — the selectively vulnerable systems a paraneoplastic process targets, and nothing else
//
// Keyed by `${level}|${part}` — see the note in vascular.js on why part alone is unsafe.
//
// `surface` is decided by COMPARTMENT, exhaustively, so no key is left undetermined:
//   root, cauda, skull_base            -> true  (thecal sac / cisternal / dural — what CSF seeding reaches)
//   visual_pathway|chiasm              -> true  (suprasellar cistern)
//   conus|medullaris                   -> true  (the conus-cauda junction is a CSF-surface site)
//   everything else                    -> false (parenchyma, or extradural: plexus, nerve, motor unit,
//                                                sympathetic chain, pupil)
// Note `plexus` is FALSE deliberately — it is extradural, outside the CSF space, so leptomeningeal
// disease does not reach it. Roots ARE true: they run in the thecal sac.
//
// ⚠ CLINICAL CONTENT AWAITING THE OWNER'S SIGN-OFF.
// Spec: docs/superpowers/specs/2026-08-15-multifocal-pattern-axis-design.md §2

export const LOBES = ["frontal", "parietal", "temporal", "occipital", "insula"];
export const SYSTEMS = ["limbic", "cerebellar", "brainstem", "DRG", "NMJ"];

export const TOPOGRAPHY = {
  "aphasia_subcortical|striatocapsular":         { lobe: null        , surface: false, system: null },
  "aphasia_subcortical|thalamic":                { lobe: null        , surface: false, system: null },
  "basal_ganglia|globus_pallidus":               { lobe: null        , surface: false, system: null },
  "basal_ganglia|striatum":                      { lobe: null        , surface: false, system: null },
  "basal_ganglia|substantia_nigra":              { lobe: null        , surface: false, system: null },
  "basal_ganglia|subthalamic":                   { lobe: null        , surface: false, system: null },
  "brainstem_aras|paramedian_tegmentum":         { lobe: null        , surface: false, system: "brainstem" },
  "cauda|equina":                                { lobe: null        , surface: true , system: null },
  "central_vestibular|nucleus":                  { lobe: null        , surface: false, system: "brainstem" },
  "cerebellum|flocculonodular":                  { lobe: null        , surface: false, system: "cerebellar" },
  "cerebellum|hemisphere":                       { lobe: null        , surface: false, system: "cerebellar" },
  "cerebellum|pancerebellar":                    { lobe: null        , surface: false, system: "cerebellar" },
  "cerebellum|vermis":                           { lobe: null        , surface: false, system: "cerebellar" },
  "cerebrum|diffuse":                            { lobe: null        , surface: false, system: null },
  "combined_degeneration|friedreich":            { lobe: null        , surface: false, system: null },
  "combined_degeneration|scd":                   { lobe: null        , surface: false, system: null },
  "conus|medullaris":                            { lobe: null        , surface: true , system: null },
  "cord|anterior":                               { lobe: null        , surface: false, system: null },
  "cord|central":                                { lobe: null        , surface: false, system: null },
  "cord|hemi":                                   { lobe: null        , surface: false, system: null },
  "cord|lateral":                                { lobe: null        , surface: false, system: null },
  "cord|posterior":                              { lobe: null        , surface: false, system: null },
  "cord|transverse":                             { lobe: null        , surface: false, system: null },
  "corpus_callosum|anterior":                    { lobe: null        , surface: false, system: null },
  "corpus_callosum|splenium":                    { lobe: null        , surface: false, system: null },
  "cortex|aca":                                  { lobe: "frontal"   , surface: false, system: null },
  "cortex|angular":                              { lobe: "parietal"  , surface: false, system: null },
  "cortex|anterior_temporal":                    { lobe: "temporal"  , surface: false, system: "limbic" },
  "cortex|aphasia_global":                       { lobe: null        , surface: false, system: null },
  "cortex|aphasia_mixed_transcortical":          { lobe: null        , surface: false, system: null },
  "cortex|arcuate":                              { lobe: null        , surface: false, system: null },
  "cortex|auditory":                             { lobe: "temporal"  , surface: false, system: null },
  "cortex|dlpfc":                                { lobe: "frontal"   , surface: false, system: null },
  "cortex|frontal_eye_field":                    { lobe: "frontal"   , surface: false, system: null },
  "cortex|fusiform":                             { lobe: "temporal"  , surface: false, system: null },
  "cortex|hand_knob":                            { lobe: "frontal"   , surface: false, system: null },
  "cortex|insula":                               { lobe: "insula"    , surface: false, system: null },
  "cortex|mca":                                  { lobe: null        , surface: false, system: null },
  "cortex|mca_inferior":                         { lobe: "temporal"  , surface: false, system: null },
  "cortex|mca_superior":                         { lobe: "frontal"   , surface: false, system: null },
  "cortex|medial_pfc":                           { lobe: "frontal"   , surface: false, system: null },
  "cortex|motor_facearm":                        { lobe: "frontal"   , surface: false, system: null },
  "cortex|motor_leg":                            { lobe: "frontal"   , surface: false, system: null },
  "cortex|occipital":                            { lobe: "occipital" , surface: false, system: null },
  "cortex|operculum":                            { lobe: "frontal"   , surface: false, system: null },
  "cortex|orbitofrontal":                        { lobe: "frontal"   , surface: false, system: null },
  "cortex|paracentral":                          { lobe: "frontal"   , surface: false, system: null },
  "cortex|parietal":                             { lobe: "parietal"  , surface: false, system: null },
  "cortex|pca":                                  { lobe: "occipital" , surface: false, system: null },
  "cortex|premotor":                             { lobe: "frontal"   , surface: false, system: null },
  "cortex|sensory_facearm":                      { lobe: "parietal"  , surface: false, system: null },
  "cortex|sensory_hand":                         { lobe: "parietal"  , surface: false, system: null },
  "cortex|sensory_leg":                          { lobe: "parietal"  , surface: false, system: null },
  "cortex|sma":                                  { lobe: "frontal"   , surface: false, system: null },
  "cortex|temporal":                             { lobe: "temporal"  , surface: false, system: null },
  "cortex|temporoparietal":                      { lobe: "temporal"  , surface: false, system: null },
  "cortex|watershed_anterior":                   { lobe: "frontal"   , surface: false, system: null },
  "cortex|watershed_posterior":                  { lobe: "occipital" , surface: false, system: null },
  "craniocervical_junction|foramen_magnum":      { lobe: null        , surface: false, system: null },
  "dorsal_midbrain|tectum":                      { lobe: null        , surface: false, system: "brainstem" },
  "guillain_mollaret|dentate":                   { lobe: null        , surface: false, system: "cerebellar" },
  "guillain_mollaret|rubral":                    { lobe: null        , surface: false, system: null },
  "guillain_mollaret|triangle":                  { lobe: null        , surface: false, system: null },
  "hypothalamus|lateral":                        { lobe: null        , surface: false, system: null },
  "hypothalamus|mammillary":                     { lobe: null        , surface: false, system: "limbic" },
  "hypothalamus|suprachiasmatic":                { lobe: null        , surface: false, system: null },
  "hypothalamus|supraoptic":                     { lobe: null        , surface: false, system: null },
  "hypothalamus|thermoregulatory":               { lobe: null        , surface: false, system: null },
  "hypothalamus|tuberal":                        { lobe: null        , surface: false, system: null },
  "hypothalamus|ventromedial":                   { lobe: null        , surface: false, system: null },
  "locked_in|ventral_pons":                      { lobe: null        , surface: false, system: "brainstem" },
  "medulla|hemi":                                { lobe: null        , surface: false, system: "brainstem" },
  "medulla|lateral":                             { lobe: null        , surface: false, system: "brainstem" },
  "medulla|medial":                              { lobe: null        , surface: false, system: "brainstem" },
  "midbrain|hemi":                               { lobe: null        , surface: false, system: "brainstem" },
  "midbrain|lateral":                            { lobe: null        , surface: false, system: "brainstem" },
  "midbrain|medial":                             { lobe: null        , surface: false, system: "brainstem" },
  "midbrain|trochlear":                          { lobe: null        , surface: false, system: "brainstem" },
  "motor_unit|anterior_horn":                    { lobe: null        , surface: false, system: null },
  "motor_unit|muscle":                           { lobe: null        , surface: false, system: null },
  "motor_unit|nmj_postsynaptic":                 { lobe: null        , surface: false, system: "NMJ" },
  "motor_unit|nmj_presynaptic":                  { lobe: null        , surface: false, system: "NMJ" },
  "nerve|axillary":                              { lobe: null        , surface: false, system: null },
  "nerve|femoral":                               { lobe: null        , surface: false, system: null },
  "nerve|lat_fem_cutaneous":                     { lobe: null        , surface: false, system: null },
  "nerve|long_thoracic":                         { lobe: null        , surface: false, system: null },
  "nerve|median_ain":                            { lobe: null        , surface: false, system: null },
  "nerve|median_carpal_tunnel":                  { lobe: null        , surface: false, system: null },
  "nerve|median_proximal":                       { lobe: null        , surface: false, system: null },
  "nerve|musculocutaneous":                      { lobe: null        , surface: false, system: null },
  "nerve|obturator":                             { lobe: null        , surface: false, system: null },
  "nerve|peroneal_common":                       { lobe: null        , surface: false, system: null },
  "nerve|peroneal_deep":                         { lobe: null        , surface: false, system: null },
  "nerve|peroneal_superficial":                  { lobe: null        , surface: false, system: null },
  "nerve|phrenic":                               { lobe: null        , surface: false, system: null },
  "nerve|pudendal":                              { lobe: null        , surface: false, system: null },
  "nerve|radial_axilla":                         { lobe: null        , surface: false, system: null },
  "nerve|radial_pin":                            { lobe: null        , surface: false, system: null },
  "nerve|radial_spiral_groove":                  { lobe: null        , surface: false, system: null },
  "nerve|saphenous":                             { lobe: null        , surface: false, system: null },
  "nerve|sciatic":                               { lobe: null        , surface: false, system: null },
  "nerve|superior_gluteal":                      { lobe: null        , surface: false, system: null },
  "nerve|suprascapular":                         { lobe: null        , surface: false, system: null },
  "nerve|sural":                                 { lobe: null        , surface: false, system: null },
  "nerve|tibial":                                { lobe: null        , surface: false, system: null },
  "nerve|ulnar_elbow":                           { lobe: null        , surface: false, system: null },
  "nerve|ulnar_wrist":                           { lobe: null        , surface: false, system: null },
  "olfactory|olfactory_groove":                  { lobe: null        , surface: false, system: null },
  "peripheral_vestibular|anterior_canal":        { lobe: null        , surface: true , system: null },
  "peripheral_vestibular|horizontal_canal":      { lobe: null        , surface: true , system: null },
  "peripheral_vestibular|labyrinth":             { lobe: null        , surface: true , system: null },
  "peripheral_vestibular|posterior_canal":       { lobe: null        , surface: true , system: null },
  "plexus|lateral_cord":                         { lobe: null        , surface: false, system: null },
  "plexus|lower_trunk":                          { lobe: null        , surface: false, system: null },
  "plexus|lumbar_plexus":                        { lobe: null        , surface: false, system: null },
  "plexus|medial_cord":                          { lobe: null        , surface: false, system: null },
  "plexus|middle_trunk":                         { lobe: null        , surface: false, system: null },
  "plexus|posterior_cord":                       { lobe: null        , surface: false, system: null },
  "plexus|sacral_plexus":                        { lobe: null        , surface: false, system: null },
  "plexus|upper_trunk":                          { lobe: null        , surface: false, system: null },
  "polyneuropathy|length_dependent":             { lobe: null        , surface: false, system: null },
  "pons|basis_pontis":                           { lobe: null        , surface: false, system: "brainstem" },
  "pons|hemi":                                   { lobe: null        , surface: false, system: "brainstem" },
  "pons|lateral":                                { lobe: null        , surface: false, system: "brainstem" },
  "pons|lateral_trigeminal":                     { lobe: null        , surface: false, system: "brainstem" },
  "pons|medial":                                 { lobe: null        , surface: false, system: "brainstem" },
  "pons|trigeminal":                             { lobe: null        , surface: false, system: "brainstem" },
  "pontomesencephalic|tegmentum":                { lobe: null        , surface: false, system: "brainstem" },
  "pseudobulbar|corticobulbar":                  { lobe: null        , surface: false, system: null },
  "pupil|ciliary_ganglion":                      { lobe: null        , surface: false, system: null },
  "pupil|cn3_compressive":                       { lobe: null        , surface: false, system: null },
  "pupil|cn3_ischaemic":                         { lobe: null        , surface: false, system: null },
  "pupil|pretectum":                             { lobe: null        , surface: false, system: null },
  "root|c3":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|c4":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|c5":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|c6":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|c7":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|c8":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|l1":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|l2":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|l3":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|l4":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|l5":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|s1":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|s2":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|s3":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|t1":                                     { lobe: null        , surface: true , system: "DRG" },
  "root|t10":                                    { lobe: null        , surface: true , system: "DRG" },
  "root|t4":                                     { lobe: null        , surface: true , system: "DRG" },
  "skull_base|carotid_space":                    { lobe: null        , surface: true , system: null },
  "skull_base|cavernous_sinus":                  { lobe: null        , surface: true , system: null },
  "skull_base|collet_sicard":                    { lobe: null        , surface: true , system: null },
  "skull_base|cpa":                              { lobe: null        , surface: true , system: null },
  "skull_base|foramen_rotundum":                 { lobe: null        , surface: true , system: null },
  "skull_base|hypoglossal_canal":                { lobe: null        , surface: true , system: null },
  "skull_base|iam":                              { lobe: null        , surface: true , system: null },
  "skull_base|iii_orbit_inf":                    { lobe: null        , surface: true , system: null },
  "skull_base|iii_orbit_sup":                    { lobe: null        , surface: true , system: null },
  "skull_base|ix_jugular":                       { lobe: null        , surface: true , system: null },
  "skull_base|jugular_foramen":                  { lobe: null        , surface: true , system: null },
  "skull_base|optic_aion":                       { lobe: null        , surface: false, system: null },
  "skull_base|optic_canal":                      { lobe: null        , surface: false, system: null },
  "skull_base|optic_neuritis":                   { lobe: null        , surface: false, system: null },
  "skull_base|orbital_apex":                     { lobe: null        , surface: true , system: null },
  "skull_base|petrous_apex":                     { lobe: null        , surface: true , system: null },
  "skull_base|sup_orbital_fissure":              { lobe: null        , surface: true , system: null },
  "skull_base|trochlear_cisternal":              { lobe: null        , surface: true , system: null },
  "skull_base|v1_division":                      { lobe: null        , surface: true , system: null },
  "skull_base|v1_petrous":                       { lobe: null        , surface: true , system: null },
  "skull_base|v3_ovale":                         { lobe: null        , surface: true , system: null },
  "skull_base|v_ganglion":                       { lobe: null        , surface: true , system: null },
  "skull_base|vi_cisternal":                     { lobe: null        , surface: true , system: null },
  "skull_base|vi_petrous_apex":                  { lobe: null        , surface: true , system: null },
  "skull_base|vii_geniculate":                   { lobe: null        , surface: true , system: null },
  "skull_base|vii_mastoid":                      { lobe: null        , surface: true , system: null },
  "skull_base|vii_parotid":                      { lobe: null        , surface: true , system: null },
  "skull_base|vii_stylomastoid":                 { lobe: null        , surface: true , system: null },
  "skull_base|vii_tympanic":                     { lobe: null        , surface: true , system: null },
  "skull_base|villaret":                         { lobe: null        , surface: true , system: null },
  "skull_base|x_jugular":                        { lobe: null        , surface: true , system: null },
  "skull_base|x_recurrent_laryngeal":            { lobe: null        , surface: true , system: null },
  "skull_base|xi_jugular":                       { lobe: null        , surface: true , system: null },
  "skull_base|xi_posterior_triangle":            { lobe: null        , surface: true , system: null },
  "skull_base|xii_neck":                         { lobe: null        , surface: true , system: null },
  "subcortex|anterior_choroidal":                { lobe: null        , surface: false, system: null },
  "subcortex|corona_radiata":                    { lobe: null        , surface: false, system: null },
  "subcortex|internal_capsule":                  { lobe: null        , surface: false, system: null },
  "subcortex|optic_radiation":                   { lobe: null        , surface: false, system: null },
  "subcortex|sensorimotor":                      { lobe: null        , surface: false, system: null },
  "subcortex|thalamus":                          { lobe: null        , surface: false, system: null },
  "sympathetic|pancoast":                        { lobe: null        , surface: false, system: null },
  "sympathetic|preganglionic":                   { lobe: null        , surface: false, system: null },
  "thalamus_arousal|paramedian":                 { lobe: null        , surface: false, system: null },
  "thalamus|limbic":                             { lobe: null        , surface: false, system: "limbic" },
  "thalamus|pulvinar":                           { lobe: null        , surface: false, system: null },
  "thalamus|vl":                                 { lobe: null        , surface: false, system: null },
  "thalamus|vpm":                                { lobe: null        , surface: false, system: null },
  "visual_pathway|chiasm":                       { lobe: null        , surface: true , system: null },
  "visual_pathway|lgn":                          { lobe: null        , surface: false, system: null },
  "visual_pathway|optic_tract":                  { lobe: null        , surface: false, system: null },
  "visual_pathway|retina":                       { lobe: null        , surface: false, system: null },
};

export function topographyOf(site) {
  return TOPOGRAPHY[`${site.level}|${site.part}`] || null;
}
