// plain-labels.js — every finding in plain words (spec 2026-09-27 §5.1). CONTENT ONLY: imports nothing, so a
// clinician reviews one file.
//
// `label` — a short noun phrase that reads mid-sentence after a side word ("right body pain loss"). Used by the
//   exam rows, the entered-finding chips, the answer card's Why line and the search.
// `note`  — a qualifier shown on the exam ROW only. It carries the strict vocabulary where a finding is chosen
//   (owner ruling 2026-09-25: arm/leg weakness mean PYRAMIDAL weakness) without lengthening the Why line.
// `less`  — less common in ED: the row sits behind its group's "Less common (n)" disclosure. Search still finds
//   it, and an entered one is always shown.
//
// REVIEW STATUS: ⚠ AWAITING CLINICAL REVIEW (round 1 of 3, spec 2026-09-27 §8).
export const PLAIN = {
  // ---- Higher function › Frontal ----
  executive_dysfunction: { label: "poor planning and sequencing" },
  abulia: { label: "apathy and reduced drive" },
  disinhibition: { label: "disinhibition" },
  limb_apraxia: { label: "limb apraxia", less: true },
  alien_limb: { label: "alien limb", less: true },
  gait_apraxia: { label: "magnetic frontal gait", less: true },
  callosal_apraxia: { label: "left-hand apraxia to command", less: true },
  // ---- Higher function › Parietal ----
  neglect: { label: "neglect of one side" },
  anosognosia: { label: "unaware of the deficit" },
  constructional_apraxia: { label: "can't copy a drawing", less: true },
  dressing_apraxia: { label: "dressing apraxia", less: true },
  ideomotor_apraxia: { label: "can't mime tool use", less: true },
  agraphia: { label: "can't write", less: true },
  acalculia: { label: "can't calculate", less: true },
  finger_agnosia: { label: "can't name fingers", less: true },
  left_right_disorientation: { label: "left-right confusion", less: true },
  optic_ataxia: { label: "misreaching under vision", less: true },
  oculomotor_apraxia: { label: "can't direct gaze to targets", less: true },
  simultanagnosia: { label: "sees one object at a time", less: true },
  tactile_anomia: { label: "left-hand tactile anomia", less: true },
  // ---- Higher function › Temporal ----
  verbal_memory_impairment: { label: "poor verbal memory" },
  nonverbal_memory_impairment: { label: "poor non-verbal memory", less: true },
  amnesia: { label: "can't form new memories" },
  hallucinations: { label: "hallucinations" },
  mood_change: { label: "episodic mood change", less: true },
  cortical_deafness: { label: "cortical deafness", less: true },
  kluver_bucy: { label: "Klüver-Bucy syndrome", less: true },
  // ---- Higher function › Occipital ----
  visual_agnosia: { label: "can't recognise objects seen", less: true },
  achromatopsia: { label: "cerebral colour blindness", less: true },
  prosopagnosia: { label: "can't recognise faces", less: true },
  alexia_without_agraphia: { label: "can't read but can write", less: true },
  cortical_blindness: { label: "cortical blindness" },
  // ---- Speech & language ----
  speech_nonfluent: { label: "non-fluent speech" },
  comprehension_impaired: { label: "poor comprehension" },
  repetition_impaired: { label: "impaired repetition" },
  naming_impaired: { label: "word-finding difficulty" },
  motor_dysprosody: { label: "flat monotone speech", less: true },
  sensory_dysprosody: { label: "can't read emotional tone", less: true },
  dysarthria: { label: "slurred speech" },
  ataxic_dysarthria: { label: "scanning (ataxic) speech", less: true },
  emotional_lability: { label: "uncontrolled laughing or crying", less: true },
  // ---- Consciousness & arousal ----
  reduced_consciousness: { label: "reduced consciousness" },
  preserved_vertical_gaze: { label: "only vertical eye movements left", less: true },
  extensor_posturing: { label: "extensor posturing" },
  // ---- Cranial nerves › I ----
  anosmia: { label: "loss of smell" },
  // ---- Cranial nerves › II ----
  optic_neuropathy: { label: "loss of vision in one eye" },
  central_scotoma: { label: "central blind spot", less: true },
  altitudinal_defect: { label: "altitudinal field loss", less: true },
  rapd: { label: "RAPD" },
  homonymous_hemianopia: { label: "half-field loss" },
  superior_quadrantanopia: { label: "upper quadrant field loss", less: true },
  inferior_quadrantanopia: { label: "lower quadrant field loss", less: true },
  bitemporal_hemianopia: { label: "bitemporal field loss" },
  macular_sparing: { label: "central vision spared", less: true },
  // ---- Cranial nerves › Acuity & fundoscopy ----
  va_reduced_no_pinhole: { label: "poor acuity not helped by pinhole" },
  va_reduced_pinhole_corrects: { label: "poor acuity corrected by pinhole" },
  papilloedema: { label: "papilloedema" },
  optic_atrophy: { label: "pale optic disc", less: true },
  retinal_pallor: { label: "pale retina with cherry-red spot", less: true },
  // ---- Cranial nerves › III / IV / VI ----
  ptosis: { label: "droopy eyelid" },
  weak_adduction: { label: "eye won't turn in" },
  weak_abduction: { label: "eye won't turn out" },
  weak_elevation: { label: "eye won't look up" },
  weak_depression: { label: "eye won't look down" },
  vertical_diplopia: { label: "vertical double vision" },
  gaze_deviation: { label: "eyes deviated to one side" },
  nystagmus_gaze_evoked: { label: "gaze-evoked nystagmus" },
  nystagmus_downbeat: { label: "downbeat nystagmus", less: true },
  nystagmus_upbeat: { label: "upbeat nystagmus", less: true },
  nystagmus_pendular: { label: "pendular nystagmus", less: true },
  // ---- Cranial nerves › V ----
  v1_sensory: { label: "numb forehead or eye (V1)", less: true },
  v2_sensory: { label: "numb cheek (V2)", less: true },
  v3_sensory: { label: "numb jaw or chin (V3)", less: true },
  face_pain_loss: { label: "face pain loss" },
  face_touch_loss: { label: "face touch loss" },
  face_sensory_loss: { label: "face numbness", note: "thalamic pattern" },
  jaw_weakness: { label: "weak jaw", less: true },
  // ---- Cranial nerves › VII ----
  facial_weakness: { label: "face droop" },
  forehead_spared: { label: "forehead spared", note: "upper motor neuron pattern" },
  forehead_involved: { label: "forehead weak too", note: "lower motor neuron pattern" },
  facial_weak_branch: { label: "one facial branch weak", less: true },
  lacrimation_loss: { label: "dry eye", less: true },
  hyperacusis: { label: "loud sounds uncomfortable", less: true },
  taste_loss: { label: "front-of-tongue taste loss", less: true },
  gustatory_loss: { label: "central taste loss", less: true },
  // ---- Cranial nerves › VIII ----
  hearing_loss: { label: "hearing loss" },
  cn8_vertigo: { label: "vertigo" },
  nystagmus_peripheral: { label: "peripheral-type nystagmus" },
  head_impulse_abnormal: { label: "abnormal head impulse" },
  nystagmus_positional_posterior: { label: "posterior-canal positional nystagmus" },
  nystagmus_positional_horizontal: { label: "horizontal-canal positional nystagmus", less: true },
  nystagmus_positional_anterior: { label: "anterior-canal positional nystagmus", less: true },
  // ---- Cranial nerves › IX–XII ----
  dysphagia: { label: "swallowing difficulty" },
  gag_afferent_loss: { label: "absent gag with numb throat", less: true },
  taste_posterior: { label: "back-of-tongue taste loss", less: true },
  palatal_weakness: { label: "weak palate", less: true },
  vocal_cord_palsy: { label: "hoarse voice" },
  weak_scm: { label: "weak head turn", less: true },
  weak_trapezius: { label: "weak shoulder shrug", less: true },
  cn12_palsy: { label: "tongue weakness" },
  // ---- Brainstem & pupils › Gaze ----
  gaze_palsy: { label: "horizontal gaze palsy" },
  ino: { label: "INO" },
  vertical_gaze_palsy: { label: "up-gaze palsy", less: true },
  skew_deviation: { label: "skew deviation" },
  lid_retraction: { label: "lid retraction", less: true },
  nystagmus_convergence_retraction: { label: "convergence-retraction nystagmus", less: true },
  // ---- Brainstem & pupils › Pupils ----
  fixed_dilated_pupil: { label: "fixed dilated pupil" },
  light_near_dissociation: { label: "light-near dissociation", less: true },
  miosis: { label: "small pupil" },
  anhidrosis_face: { label: "no sweating on the face", less: true },
  anhidrosis_body: { label: "no sweating on one side of the body", less: true },
  // ---- Motor › By limb ----
  weak_arm: { label: "arm weakness", note: "upper motor neuron pattern" },
  weak_leg: { label: "leg weakness", note: "upper motor neuron pattern" },
  weak_hand: { label: "hand weakness", note: "isolated hand or fingers" },
  proximal_weakness: { label: "proximal weakness", note: "both sides, limb-girdle" },
  distal_motor_weakness: { label: "distal weakness", note: "both sides, length-dependent" },
  lmn_weakness: { label: "floppy weakness", note: "lower motor neuron pattern" },
  weak_diaphragm: { label: "weak diaphragm", less: true },
  // ---- Motor › By myotome ----
  weak_shoulder_abduction: { label: "weak shoulder abduction" },
  weak_shoulder_external_rotation: { label: "weak shoulder external rotation", less: true },
  weak_scapular_stabilisation: { label: "scapular winging", less: true },
  weak_elbow_flexion: { label: "weak elbow flexion" },
  weak_elbow_extension: { label: "weak elbow extension" },
  weak_forearm_supination: { label: "weak supination", less: true },
  weak_forearm_pronation: { label: "weak pronation", less: true },
  weak_wrist_extension: { label: "wrist drop" },
  weak_wrist_flexion: { label: "weak wrist flexion", less: true },
  weak_finger_extension: { label: "weak finger extension", less: true },
  weak_finger_flexion: { label: "weak grip", less: true },
  weak_finger_abduction: { label: "weak finger spreading" },
  weak_thumb_abduction: { label: "weak thumb abduction", less: true },
  weak_thumb_adduction: { label: "weak thumb adduction (Froment's)", less: true },
  ulnar_claw: { label: "ulnar claw hand", less: true },
  weak_hip_flexion: { label: "weak hip flexion" },
  weak_hip_adduction: { label: "weak hip adduction", less: true },
  weak_hip_abduction: { label: "weak hip abduction" },
  weak_knee_extension: { label: "weak knee extension" },
  weak_knee_flexion: { label: "weak knee flexion", less: true },
  weak_ankle_dorsiflexion: { label: "foot drop" },
  weak_great_toe_extension: { label: "weak big-toe lift" },
  weak_foot_eversion: { label: "weak foot eversion" },
  weak_foot_inversion: { label: "weak foot inversion" },
  weak_ankle_plantarflexion: { label: "weak push-off (plantarflexion)" },
  weak_toe_flexion: { label: "weak toe curl", less: true },
  // ---- Tone ----
  spasticity: { label: "spasticity" },
  rigidity: { label: "rigidity" },
  hypotonia: { label: "floppy tone" },
  // ---- Reflexes ----
  babinski: { label: "up-going plantar" },
  hoffmann: { label: "Hoffmann's sign" },
  umn_signs: { label: "brisk reflexes and up-going plantars" },
  reflex_biceps_loss: { label: "absent biceps jerk" },
  reflex_brachioradialis_loss: { label: "absent supinator jerk", less: true },
  reflex_triceps_loss: { label: "absent triceps jerk" },
  reflex_knee_loss: { label: "absent knee jerk" },
  reflex_ankle_loss: { label: "absent ankle jerk" },
  grasp_reflex: { label: "grasp reflex", less: true },
  palmomental: { label: "palmomental reflex", less: true },
  anal_wink_loss: { label: "absent anal wink" },
  bulbocavernosus_loss: { label: "absent bulbocavernosus reflex", less: true },
  // ---- Wasting & fasciculations ----
  wasting: { label: "muscle wasting" },
  fasciculations: { label: "fasciculations" },
  // ---- Sensation › Pain & temperature ----
  spinothalamic: { label: "body pain loss", note: "pain and temperature" },
  thalamic_pain: { label: "central post-stroke pain", less: true },
  // ---- Sensation › Vibration & proprioception ----
  dorsal_sensory: { label: "vibration and position loss" },
  sensory_ataxia: { label: "positive Romberg" },
  // ---- Sensation › Cortical ----
  cortical_sensory_arm: { label: "arm cortical sensory loss" },
  cortical_sensory_leg: { label: "leg cortical sensory loss" },
  cortical_sensory_hand: { label: "hand and mouth cortical sensory loss", less: true },
  // ---- Sensation › Dermatomal ----
  sensory_c3: { label: "C3 numbness", less: true },
  sensory_c4: { label: "C4 numbness", less: true },
  sensory_c5: { label: "C5 numbness" },
  sensory_c6: { label: "C6 numbness" },
  sensory_c7: { label: "C7 numbness" },
  sensory_c8: { label: "C8 numbness" },
  sensory_t1: { label: "T1 numbness", less: true },
  sensory_t4: { label: "T4 numbness", less: true },
  sensory_t10: { label: "T10 numbness", less: true },
  sensory_l1: { label: "L1 numbness", less: true },
  sensory_l2: { label: "L2 numbness", less: true },
  sensory_l3: { label: "L3 numbness", less: true },
  sensory_l4: { label: "L4 numbness" },
  sensory_l5: { label: "L5 numbness" },
  sensory_s1: { label: "S1 numbness" },
  sensory_s2: { label: "S2 numbness", less: true },
  sensory_s3: { label: "S3 numbness", less: true },
  radicular_pain: { label: "sciatica-type root pain" },
  // ---- Sensation › Peripheral-nerve territory ----
  axillary_sensory: { label: "badge-area numbness", note: "axillary nerve", less: true },
  musculocutaneous_sensory: { label: "lateral forearm numbness", note: "musculocutaneous nerve", less: true },
  radial_sensory: { label: "snuffbox numbness", note: "radial nerve" },
  median_sensory: { label: "thumb-side finger numbness", note: "median nerve" },
  median_palmar_sensory: { label: "palm numbness", note: "palmar branch of median", less: true },
  ulnar_sensory: { label: "little-finger numbness", note: "ulnar nerve" },
  ulnar_dorsal_sensory: { label: "back-of-hand ulnar numbness", less: true },
  femoral_sensory: { label: "front-of-thigh numbness", note: "femoral nerve", less: true },
  obturator_sensory: { label: "inner-thigh numbness", note: "obturator nerve", less: true },
  lat_fem_cutaneous_sensory: { label: "outer-thigh numbness", note: "meralgia paraesthetica" },
  saphenous_sensory: { label: "inner-shin numbness", note: "saphenous nerve", less: true },
  sciatic_sensory: { label: "below-knee numbness", note: "sciatic nerve", less: true },
  peroneal_sensory: { label: "top-of-foot numbness", note: "common peroneal nerve" },
  deep_peroneal_sensory: { label: "first web-space numbness", note: "deep peroneal nerve", less: true },
  tibial_sensory: { label: "sole numbness", note: "tibial nerve", less: true },
  sural_sensory: { label: "outer-foot numbness", note: "sural nerve", less: true },
  // ---- Sensation › Glove-and-stocking ----
  distal_sensory_loss: { label: "glove-and-stocking numbness" },
  // ---- Sensation › Sensory level / cord ----
  suspended_sensory: { label: "cape-like pain loss", less: true },
  saddle_anaesthesia: { label: "saddle numbness" },
  // ---- Coordination & cerebellar ----
  limb_ataxia: { label: "limb ataxia" },
  dysmetria: { label: "past-pointing" },
  dysdiadochokinesis: { label: "slow alternating movements" },
  intention_tremor: { label: "intention tremor" },
  truncal_ataxia: { label: "truncal ataxia", note: "wide-based, unsteady gait" },
  tremor_rubral: { label: "rubral tremor", less: true },
  palatal_tremor: { label: "palatal tremor", less: true },
  // ---- Movement disorders ----
  bradykinesia: { label: "slowness of movement" },
  rest_tremor: { label: "rest tremor" },
  chorea: { label: "chorea" },
  dystonia: { label: "dystonia" },
  hemiballismus: { label: "hemiballismus" },
  thalamic_tremor: { label: "thalamic tremor", less: true },
  // ---- Fatiguability / augmentation ----
  fatigable_weakness: { label: "weakness that tires with use" },
  fatigable_ocular: { label: "fatigable ptosis and double vision" },
  facilitating_weakness: { label: "weakness that improves with effort", less: true },
  autonomic_features: { label: "dry mouth and constipation", note: "autonomic", less: true },
  // ---- Autonomic, sphincter & hypothalamic ----
  sphincter_dysfunction: { label: "bladder or bowel dysfunction" },
  urinary_incontinence: { label: "urinary incontinence", note: "frontal pattern" },
  diabetes_insipidus: { label: "diabetes insipidus", less: true },
  thermodysregulation: { label: "temperature dysregulation", less: true },
  hyperphagia: { label: "hyperphagia", less: true },
  narcolepsy: { label: "excessive sleepiness", less: true },
  circadian_disruption: { label: "sleep-wake disruption", less: true },
  endocrine_dysfunction: { label: "pituitary hormone dysfunction", less: true },
  // ---- Functional signs (positive) ----
  hoovers_sign: { label: "Hoover's sign" },
  give_way_weakness: { label: "give-way weakness" },
  entrainment: { label: "tremor entrains", less: true },
  exam_inconsistency: { label: "inconsistent examination", less: true },
};

// The plain label, or the id made readable if a finding is ever added without one (the suite fails first).
export const plainLabel = f => (PLAIN[f] && PLAIN[f].label) || String(f).replace(/_/g, " ");
