// plain-labels.js — every finding in plain words (spec 2026-09-27 §5.1). CONTENT ONLY: imports nothing, so a
// clinician reviews one file.
//
// `label` — a short noun phrase that reads mid-sentence after a side word ("right body pain loss"). Used by the
//   exam rows, the entered-finding chips, the answer card's Why line and the search.
// `term`  — the proper clinical name, shown in brackets after the plain label wherever the label shows ("can't
//   calculate (acalculia)"); omitted where the plain label already is the proper name (owner ruling 2026-09-29).
// `note`  — a qualifier shown on the exam ROW only. It carries the strict vocabulary where a finding is chosen
//   (owner ruling 2026-09-25: arm/leg weakness mean PYRAMIDAL weakness) without lengthening the Why line.
// `less`  — less common in ED: the row sits behind its group's "Less common (n)" disclosure. Search still finds
//   it, and an entered one is always shown.
//
// REVIEW STATUS: ✅ SIGNED OFF by the owner (a clinician), 2026-09-29 — review round 1 of 3, in two passes: the
// first produced eight rulings (proper names in brackets; Klüver-Bucy; anterior 2/3; hypotonia; brisk reflexes apart
// from the plantar; a down-going plantar; central post-stroke pain removed; the autonomic split), the second approved.
export const PLAIN = {
  // ---- Higher function › Frontal ----
  executive_dysfunction: { label: "poor planning and sequencing", term: "executive dysfunction" },
  abulia: { label: "apathy and reduced drive", term: "abulia" },
  disinhibition: { label: "disinhibition" },
  limb_apraxia: { label: "limb apraxia", less: true },
  alien_limb: { label: "alien limb", less: true },
  gait_apraxia: { label: "magnetic frontal gait", term: "gait apraxia", less: true },
  callosal_apraxia: { label: "left-hand apraxia to command", term: "callosal apraxia", less: true },
  // ---- Higher function › Parietal ----
  neglect: { label: "neglect of one side", term: "hemispatial neglect" },
  anosognosia: { label: "unaware of the deficit", term: "anosognosia" },
  constructional_apraxia: { label: "can't copy a drawing", term: "constructional apraxia", less: true },
  dressing_apraxia: { label: "dressing apraxia", less: true },
  ideomotor_apraxia: { label: "can't mime tool use", term: "ideomotor apraxia", less: true },
  agraphia: { label: "can't write", term: "agraphia", less: true },
  acalculia: { label: "can't calculate", term: "acalculia", less: true },
  finger_agnosia: { label: "can't name fingers", term: "finger agnosia", less: true },
  left_right_disorientation: { label: "left-right confusion", term: "left-right disorientation", less: true },
  optic_ataxia: { label: "misreaching under vision", term: "optic ataxia", less: true },
  oculomotor_apraxia: { label: "can't direct gaze to targets", term: "oculomotor apraxia", less: true },
  simultanagnosia: { label: "sees one object at a time", term: "simultanagnosia", less: true },
  tactile_anomia: { label: "left-hand tactile anomia", less: true },
  // ---- Higher function › Temporal ----
  verbal_memory_impairment: { label: "poor verbal memory" },
  nonverbal_memory_impairment: { label: "poor non-verbal memory", less: true },
  amnesia: { label: "can't form new memories", term: "anterograde amnesia" },
  hallucinations: { label: "hallucinations" },
  mood_change: { label: "episodic mood change", less: true },
  cortical_deafness: { label: "cortical deafness", less: true },
  kluver_bucy: { label: "hyperorality and hypersexuality", term: "Klüver-Bucy syndrome", less: true },
  // ---- Higher function › Occipital ----
  visual_agnosia: { label: "can't recognise objects seen", term: "visual agnosia", less: true },
  achromatopsia: { label: "cerebral colour blindness", term: "achromatopsia", less: true },
  prosopagnosia: { label: "can't recognise faces", term: "prosopagnosia", less: true },
  alexia_without_agraphia: { label: "can't read but can write", term: "alexia without agraphia", less: true },
  cortical_blindness: { label: "cortical blindness with unawareness", term: "Anton syndrome" },
  // ---- Speech & language ----
  speech_nonfluent: { label: "non-fluent speech", term: "non-fluent aphasia" },
  comprehension_impaired: { label: "poor comprehension", term: "receptive aphasia" },
  repetition_impaired: { label: "impaired repetition" },
  naming_impaired: { label: "word-finding difficulty", term: "anomia" },
  motor_dysprosody: { label: "flat monotone speech", term: "motor aprosodia", less: true },
  sensory_dysprosody: { label: "can't read emotional tone", term: "sensory aprosodia", less: true },
  dysarthria: { label: "slurred speech", term: "dysarthria" },
  ataxic_dysarthria: { label: "scanning speech", term: "ataxic dysarthria", less: true },
  emotional_lability: { label: "uncontrolled laughing or crying", term: "pseudobulbar affect", less: true },
  // ---- Consciousness & arousal ----
  reduced_consciousness: { label: "reduced consciousness" },
  preserved_vertical_gaze: { label: "only vertical eye movements left", term: "locked-in syndrome", less: true },
  extensor_posturing: { label: "extensor posturing", term: "decerebrate posturing" },
  // ---- Cranial nerves › I ----
  anosmia: { label: "loss of smell", term: "anosmia" },
  // ---- Cranial nerves › II ----
  optic_neuropathy: { label: "loss of vision in one eye" },
  central_scotoma: { label: "central blind spot", term: "central scotoma", less: true },
  altitudinal_defect: { label: "altitudinal field loss", less: true },
  rapd: { label: "pupil dilates on swinging light", term: "relative afferent pupillary defect" },
  homonymous_hemianopia: { label: "half-field loss", term: "homonymous hemianopia" },
  superior_quadrantanopia: { label: "upper quadrant field loss", term: "superior quadrantanopia", less: true },
  inferior_quadrantanopia: { label: "lower quadrant field loss", term: "inferior quadrantanopia", less: true },
  bitemporal_hemianopia: { label: "bitemporal field loss", term: "bitemporal hemianopia" },
  macular_sparing: { label: "central vision spared", term: "macular sparing", less: true },
  // ---- Cranial nerves › Acuity & fundoscopy ----
  va_reduced_no_pinhole: { label: "poor acuity not helped by pinhole" },
  va_reduced_pinhole_corrects: { label: "poor acuity corrected by pinhole", term: "refractive error" },
  papilloedema: { label: "papilloedema" },
  optic_atrophy: { label: "pale optic disc", term: "optic atrophy", less: true },
  retinal_pallor: { label: "pale retina with cherry-red spot", term: "retinal pallor", less: true },
  // ---- Cranial nerves › III / IV / VI ----
  ptosis: { label: "droopy eyelid", term: "ptosis" },
  weak_adduction: { label: "eye won't turn in", term: "adduction deficit" },
  weak_abduction: { label: "eye won't turn out", term: "abduction deficit" },
  weak_elevation: { label: "eye won't look up", term: "elevation deficit" },
  weak_depression: { label: "eye won't look down", term: "depression deficit" },
  vertical_diplopia: { label: "vertical double vision", term: "vertical diplopia" },
  gaze_deviation: { label: "eyes deviated to one side", term: "conjugate gaze deviation" },
  nystagmus_gaze_evoked: { label: "gaze-evoked nystagmus" },
  nystagmus_downbeat: { label: "downbeat nystagmus", less: true },
  nystagmus_upbeat: { label: "upbeat nystagmus", less: true },
  nystagmus_pendular: { label: "pendular nystagmus", less: true },
  // ---- Cranial nerves › V ----
  v1_sensory: { label: "numb forehead or eye", term: "V1 sensory loss", less: true },
  v2_sensory: { label: "numb cheek", term: "V2 sensory loss", less: true },
  v3_sensory: { label: "numb jaw or chin", term: "V3 sensory loss", less: true },
  face_pain_loss: { label: "face pain loss" },
  face_touch_loss: { label: "face touch loss" },
  face_sensory_loss: { label: "face numbness", note: "thalamic pattern" },
  jaw_weakness: { label: "weak jaw", term: "masseter weakness", less: true },
  // ---- Cranial nerves › VII ----
  facial_weakness: { label: "face droop", term: "facial weakness" },
  forehead_spared: { label: "forehead spared", note: "upper motor neuron pattern" },
  forehead_involved: { label: "forehead weak too", note: "lower motor neuron pattern" },
  facial_weak_branch: { label: "one facial branch weak", term: "partial facial palsy", less: true },
  lacrimation_loss: { label: "dry eye", term: "reduced lacrimation", less: true },
  hyperacusis: { label: "loud sounds uncomfortable", term: "hyperacusis", less: true },
  taste_loss: { label: "taste loss over anterior 2/3 of tongue", less: true },
  gustatory_loss: { label: "central taste loss", less: true },
  // ---- Cranial nerves › VIII ----
  hearing_loss: { label: "hearing loss", term: "sensorineural hearing loss" },
  cn8_vertigo: { label: "vertigo" },
  nystagmus_peripheral: { label: "peripheral-type nystagmus" },
  head_impulse_abnormal: { label: "abnormal head impulse", term: "positive head impulse test" },
  nystagmus_positional_posterior: { label: "posterior-canal positional nystagmus", term: "positive Dix-Hallpike" },
  nystagmus_positional_horizontal: { label: "horizontal-canal positional nystagmus", term: "positive supine roll test", less: true },
  nystagmus_positional_anterior: { label: "anterior-canal positional nystagmus", less: true },
  // ---- Cranial nerves › IX–XII ----
  dysphagia: { label: "swallowing difficulty", term: "dysphagia" },
  gag_afferent_loss: { label: "absent gag with numb throat", term: "glossopharyngeal palsy", less: true },
  taste_posterior: { label: "taste loss over posterior 1/3 of tongue", less: true },
  palatal_weakness: { label: "weak palate", term: "palatal palsy", less: true },
  vocal_cord_palsy: { label: "hoarse voice", term: "vocal cord palsy" },
  weak_scm: { label: "weak head turn", term: "sternocleidomastoid weakness", less: true },
  weak_trapezius: { label: "weak shoulder shrug", term: "trapezius weakness", less: true },
  cn12_palsy: { label: "tongue weakness", term: "hypoglossal palsy" },
  // ---- Brainstem & pupils › Gaze ----
  gaze_palsy: { label: "horizontal gaze palsy" },
  ino: { label: "eye lags turning in on side gaze", term: "internuclear ophthalmoplegia" },
  vertical_gaze_palsy: { label: "up-gaze palsy", term: "vertical gaze palsy", less: true },
  skew_deviation: { label: "skew deviation" },
  lid_retraction: { label: "lid retraction", term: "Collier's sign", less: true },
  nystagmus_convergence_retraction: { label: "convergence-retraction nystagmus", less: true },
  // ---- Brainstem & pupils › Pupils ----
  fixed_dilated_pupil: { label: "fixed dilated pupil" },
  light_near_dissociation: { label: "light-near dissociation", less: true },
  miosis: { label: "small pupil", term: "miosis" },
  anhidrosis_face: { label: "no sweating on the face", term: "facial anhidrosis", less: true },
  anhidrosis_body: { label: "no sweating on one side of the body", term: "hemibody anhidrosis", less: true },
  // ---- Motor › By limb ----
  weak_arm: { label: "arm weakness", note: "upper motor neuron pattern" },
  weak_leg: { label: "leg weakness", note: "upper motor neuron pattern" },
  weak_hand: { label: "hand weakness", note: "isolated hand or fingers" },
  proximal_weakness: { label: "proximal weakness", note: "both sides, limb-girdle" },
  distal_motor_weakness: { label: "distal weakness", note: "both sides, length-dependent" },
  lmn_weakness: { label: "flaccid weakness", note: "lower motor neuron pattern" },
  weak_diaphragm: { label: "weak diaphragm", less: true },
  // ---- Motor › By myotome ----
  weak_shoulder_abduction: { label: "weak shoulder abduction" },
  weak_shoulder_external_rotation: { label: "weak shoulder external rotation", less: true },
  weak_scapular_stabilisation: { label: "scapular winging", less: true },
  weak_elbow_flexion: { label: "weak elbow flexion" },
  weak_elbow_extension: { label: "weak elbow extension" },
  weak_forearm_supination: { label: "weak supination", less: true },
  weak_forearm_pronation: { label: "weak pronation", less: true },
  weak_wrist_extension: { label: "wrist drop", term: "weak wrist extension" },
  weak_wrist_flexion: { label: "weak wrist flexion", less: true },
  weak_finger_extension: { label: "weak finger extension", less: true },
  weak_finger_flexion: { label: "weak grip", term: "weak finger flexion", less: true },
  weak_finger_abduction: { label: "weak finger spreading", term: "weak finger abduction" },
  weak_thumb_abduction: { label: "weak thumb abduction", less: true },
  weak_thumb_adduction: { label: "weak thumb pinch", term: "Froment's sign", less: true },
  ulnar_claw: { label: "ulnar claw hand", less: true },
  weak_hip_flexion: { label: "weak hip flexion" },
  weak_hip_adduction: { label: "weak hip adduction", less: true },
  weak_hip_abduction: { label: "weak hip abduction" },
  weak_knee_extension: { label: "weak knee extension" },
  weak_knee_flexion: { label: "weak knee flexion", less: true },
  weak_ankle_dorsiflexion: { label: "foot drop", term: "weak ankle dorsiflexion" },
  weak_great_toe_extension: { label: "weak big-toe lift", term: "weak great-toe extension" },
  weak_foot_eversion: { label: "weak foot eversion" },
  weak_foot_inversion: { label: "weak foot inversion" },
  weak_ankle_plantarflexion: { label: "weak push-off", term: "weak plantarflexion" },
  weak_toe_flexion: { label: "weak toe curl", term: "weak toe flexion", less: true },
  // ---- Tone ----
  spasticity: { label: "spasticity" },
  rigidity: { label: "rigidity" },
  hypotonia: { label: "reduced tone", term: "hypotonia" },
  // ---- Reflexes ----
  babinski: { label: "up-going plantar", term: "Babinski sign" },
  plantar_flexor: { label: "down-going plantar", term: "flexor plantar response" },
  hoffmann: { label: "thumb flexes on nail flick", term: "Hoffmann's sign" },
  hyperreflexia: { label: "brisk reflexes", term: "hyperreflexia" },
  reflex_biceps_loss: { label: "absent biceps jerk" },
  reflex_brachioradialis_loss: { label: "absent supinator jerk", less: true },
  reflex_triceps_loss: { label: "absent triceps jerk" },
  reflex_knee_loss: { label: "absent knee jerk" },
  reflex_ankle_loss: { label: "absent ankle jerk" },
  grasp_reflex: { label: "grasp reflex", less: true },
  palmomental: { label: "palmomental reflex", less: true },
  anal_wink_loss: { label: "absent anal wink" },
  bulbocavernosus_loss: { label: "absent bulbocavernosus reflex", less: true },
  // ---- Wasting & fasciculations ----
  wasting: { label: "muscle wasting" },
  fasciculations: { label: "fasciculations" },
  // ---- Sensation › Pain & temperature ----
  spinothalamic: { label: "body pain loss", term: "spinothalamic loss" },
  // ---- Sensation › Vibration & proprioception ----
  dorsal_sensory: { label: "vibration and position loss", term: "dorsal column loss" },
  sensory_ataxia: { label: "unsteady with eyes closed", term: "Romberg sign" },
  // ---- Sensation › Cortical ----
  cortical_sensory_arm: { label: "arm cortical sensory loss" },
  cortical_sensory_leg: { label: "leg cortical sensory loss" },
  cortical_sensory_hand: { label: "hand and mouth cortical sensory loss", less: true },
  // ---- Sensation › Dermatomal ----
  sensory_c3: { label: "C3 numbness", less: true },
  sensory_c4: { label: "C4 numbness", less: true },
  sensory_c5: { label: "C5 numbness" },
  sensory_c6: { label: "C6 numbness" },
  sensory_c7: { label: "C7 numbness" },
  sensory_c8: { label: "C8 numbness" },
  sensory_t1: { label: "T1 numbness", less: true },
  sensory_t4: { label: "T4 numbness", less: true },
  sensory_t10: { label: "T10 numbness", less: true },
  sensory_l1: { label: "L1 numbness", less: true },
  sensory_l2: { label: "L2 numbness", less: true },
  sensory_l3: { label: "L3 numbness", less: true },
  sensory_l4: { label: "L4 numbness" },
  sensory_l5: { label: "L5 numbness" },
  sensory_s1: { label: "S1 numbness" },
  sensory_s2: { label: "S2 numbness", less: true },
  sensory_s3: { label: "S3 numbness", less: true },
  radicular_pain: { label: "sciatica-type root pain", term: "radicular pain" },
  // ---- Sensation › Peripheral-nerve territory ----
  axillary_sensory: { label: "badge-area numbness", term: "axillary nerve", less: true },
  musculocutaneous_sensory: { label: "lateral forearm numbness", term: "musculocutaneous nerve", less: true },
  radial_sensory: { label: "snuffbox numbness", term: "radial nerve" },
  median_sensory: { label: "thumb-side finger numbness", term: "median nerve" },
  median_palmar_sensory: { label: "palm numbness", term: "palmar branch of median", less: true },
  ulnar_sensory: { label: "little-finger numbness", term: "ulnar nerve" },
  ulnar_dorsal_sensory: { label: "back-of-hand ulnar numbness", term: "dorsal ulnar cutaneous", less: true },
  femoral_sensory: { label: "front-of-thigh numbness", term: "femoral nerve", less: true },
  obturator_sensory: { label: "inner-thigh numbness", term: "obturator nerve", less: true },
  lat_fem_cutaneous_sensory: { label: "outer-thigh numbness", term: "meralgia paraesthetica" },
  saphenous_sensory: { label: "inner-shin numbness", term: "saphenous nerve", less: true },
  sciatic_sensory: { label: "below-knee numbness", term: "sciatic nerve", less: true },
  peroneal_sensory: { label: "top-of-foot numbness", term: "common peroneal nerve" },
  deep_peroneal_sensory: { label: "first web-space numbness", term: "deep peroneal nerve", less: true },
  tibial_sensory: { label: "sole numbness", term: "tibial nerve", less: true },
  sural_sensory: { label: "outer-foot numbness", term: "sural nerve", less: true },
  // ---- Sensation › Glove-and-stocking ----
  distal_sensory_loss: { label: "glove-and-stocking numbness" },
  // ---- Sensation › Sensory level / cord ----
  suspended_sensory: { label: "cape-like pain loss", term: "suspended sensory loss", less: true },
  saddle_anaesthesia: { label: "saddle numbness", term: "saddle anaesthesia" },
  // ---- Coordination & cerebellar ----
  limb_ataxia: { label: "limb ataxia" },
  dysmetria: { label: "past-pointing", term: "dysmetria" },
  dysdiadochokinesis: { label: "slow alternating movements", term: "dysdiadochokinesis" },
  intention_tremor: { label: "intention tremor" },
  truncal_ataxia: { label: "truncal ataxia", note: "wide-based, unsteady gait" },
  tremor_rubral: { label: "rubral tremor", term: "Holmes tremor", less: true },
  palatal_tremor: { label: "palatal tremor", less: true },
  // ---- Movement disorders ----
  bradykinesia: { label: "slowness of movement", term: "bradykinesia" },
  rest_tremor: { label: "rest tremor" },
  chorea: { label: "chorea" },
  dystonia: { label: "dystonia" },
  hemiballismus: { label: "hemiballismus" },
  thalamic_tremor: { label: "thalamic tremor", less: true },
  // ---- Fatiguability / augmentation ----
  fatigable_weakness: { label: "weakness that tires with use", term: "fatigable weakness" },
  fatigable_ocular: { label: "fatigable ptosis and double vision" },
  facilitating_weakness: { label: "weakness that improves with effort", term: "post-exercise facilitation", less: true },
  // ---- Autonomic, sphincter & hypothalamic ----
  sphincter_dysfunction: { label: "bladder or bowel dysfunction" },
  dry_mouth: { label: "dry mouth", term: "xerostomia" },
  constipation: { label: "constipation" },
  erectile_dysfunction: { label: "erectile dysfunction" },
  labile_blood_pressure: { label: "labile blood pressure", note: "or postural hypotension" },
  arrhythmia: { label: "unstable heart rhythm", term: "arrhythmia" },
  urinary_incontinence: { label: "urinary incontinence", note: "frontal pattern" },
  diabetes_insipidus: { label: "diabetes insipidus", less: true },
  thermodysregulation: { label: "temperature dysregulation", less: true },
  hyperphagia: { label: "hyperphagia", less: true },
  narcolepsy: { label: "excessive sleepiness", term: "hypersomnolence", less: true },
  circadian_disruption: { label: "sleep-wake disruption", less: true },
  endocrine_dysfunction: { label: "pituitary hormone dysfunction", less: true },
  // ---- Functional signs (positive) ----
  hoovers_sign: { label: "hip extension returns on distraction", term: "Hoover's sign" },
  give_way_weakness: { label: "give-way weakness" },
  entrainment: { label: "tremor matches a tapped rhythm", term: "entrainment", less: true },
  exam_inconsistency: { label: "inconsistent examination", less: true },
};

// The plain label, or the id made readable if a finding is ever added without one (the suite fails first).
export const plainLabel = f => (PLAIN[f] && PLAIN[f].label) || String(f).replace(/_/g, " ");
// What the app SHOWS: the plain label with its proper name in brackets (owner ruling 2026-09-29).
export const displayLabel = f => PLAIN[f] && PLAIN[f].term ? `${plainLabel(f)} (${PLAIN[f].term})` : plainLabel(f);
