"""svg2mod.py — turn an adopted plate into an ES module of path data.

The diagram builder is a PURE, SYNCHRONOUS, DOM-FREE string function, which is why it is testable in node.
It therefore cannot fetch() a plate at runtime, and this project has no build step. So a plate becomes a
committed JS module: generation happens here, once, and the app just imports a string.
"""
import re, sys, os

src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(src).read()
vb = re.search(r'viewBox="([^"]+)"', s).group(1)
inner = s[s.index("<g "):s.rindex("</g>") + 4]
inner = re.sub(r"\s+", " ", inner).strip()
mid = sys.argv[4] if len(sys.argv) > 4 else "0"
open(dst, "w").write(
    f"// GENERATED by tools/trace/svg2mod.py from {os.path.basename(src)} — do not hand-edit.\n"
    f"// Public domain plate, traced. Regenerate rather than tweak.\n"
    f'export const VIEWBOX = "{vb}";\n'
    f"export const MIDLINE = {mid};\n"
    "export const PATHS = `" + inner.replace("\\", "\\\\").replace("`", "\\`") + "`;\n"
)
print(f"wrote {dst} ({len(inner)} chars, viewBox {vb}, midline {mid})")
